### ISSUE TITLE
Ubuntu image tests failures

### ISSUE THREAD

**Issue by kajiya3141** [GoogleCloudPlatform/guest-test-infra#974]
Hey all!

We've had this test suite in our internal pipelines for a while now when building/testing Ubuntu cloud images for GCE. However, there are a few tests that repeatedly fail, and on further inspection I believe they're either false positives or "not applicable" to Ubuntu. What we're doing internally at the moment is skipping these tests (using the `--exclude` flag on `docker run gcr.io/gcp-guest/cloud-image-tests...`) but the issue with this is that it skips the whole suite, which is a shame as there are good tests in these suites that are also being skipped. I've added details below of the failing tests - please let me know if you need any more info.

All the best!
Chlo

* `verifySSHConfig()` fails due to `PermitRootLogin` apparently not being set  (`image_security_test.go:133: 
   &#34;PermitRootLogin&#34; was not set to &#34;no&#34; or &#34;without-password&#34;`). However, in Ubuntu [the 
   default is `prohibit-password`](https://manpages.ubuntu.com/manpages/focal/en/man5/sshd_config.5.html)?

* `TestHostsFile()` fails due to `/etc/hosts does not contain host record` but I think this test should be skipped for Ubuntu? FWIW here's an example GCE Ubuntu `/etc/hosts` file:
    ````
    ubuntu@kajiya-testing:~$ cat /etc/hosts
    127.0.0.1 localhost
    # The following lines are desirable for IPv6 capable hosts
    ::1 ip6-localhost ip6-loopback
    fe00::0 ip6-localnet
    ff00::0 ip6-mcastprefix
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters
    ff02::3 ip6-allhosts
    169.254.169.254 metadata.google.internal metadata
    ````
* `TestArePackagesLegal()` surfaces a couple of errors: `/usr/share/doc/libcanberra0/copyright`, 
   `/usr/share/doc/libnspr4/copyright` and `/usr/share/doc/python3-serial/copyright` - we may need to increase the scope of the `var licenses` strings globs?

* `TestGetentPasswdOsloginUser()` and `TestGetentPasswdOsloginUID()` both surface: `getent command failed exit status 2` 
   while `TestGetentPasswdAllUsers()` returns: `getent passwd output does not contain 
   sa_105020877179577573373:*:3651018652:3651018652::/home/sa_105020877179577573373` - I'll be honest I'm not sure 
   why this one is failing at first glace, but FWIW we do test `getent` internally on GCE images :smile: (We verify `"getent passwd 
   {} | cut -d: -f6".format(user)` for each user in the instance's metadata ssh keys).

* `testShutdownScriptTimeLinux()` returns `shut down time is 89 which is less than 110 seconds` - I understand the sentiment for this test but we also test this internally as well. We run an instance with a `shutdown-script` and check that the correct file was created. However, our internal cutoff time is `30 seconds` instead.

**Comment by a-crate** [comment]
Thanks for the feedback Chlo! This is a great way to identify our deficiencies in the Ubuntu environment.

* `verifySSHConfig()`

Right now we are simply reading the config file, discarding the comments, and parsing what's left. This whole approach is clearly brittle and I think it would also break if you put two spaces instead of one on that line. I'll implement a more robust approach where we check the effective configuration.

* `TestHostsFile()`

This is supposed to be skipped on Ubuntu. Right now we skip the test if the image name contains ubuntu, can you share the images this isn't being skipped on?

* `TestArePackagesLegal()`

I'll take a look at updating these, at a glance they should be covered by the existing regexps but obviously there's some mistaken assumptions here.

* `TestGetentPasswdOsloginUser()` and `TestGetentPasswdOsloginUID()`

The oslogin suite requires some pretty specialized setup involving service accounts and org policies. I'm under the impression that it needs org-level setup to run the test correctly. I'd suggest that you should continue to filter this suite out and if you want to create a separate org and run this suite we can get setup instructions for this. In the meantime I'll update the documentation to clarify this.

* `testShutdownScriptTimeLinux()`

Can you share the hash of the docker image you are getting this from? I think this is a bug, 89 seconds should be passing, anything over 80 is acceptable.

**Comment by a-crate** [comment]
#975 has updated some documentation, including setup instructions for oslogin in `imagetest/test_suites/oslogin/README.md`

**Comment by a-crate** [comment]
#980 should address `verifySSHConfig()` 
#981 should address `TestArePackagesLegal()`

**Comment by kajiya3141** [comment]
Thanks @a-crate for the feedback and the PRs! :smile: Between those and the increased docs our pipelines are running much smoother - I'll close this now. Thanks again!
